import Head from "next/head";
import Page from "./form";
import Image from "next/image";

import { AiFillLinkedin, AiFillGithub, AiFillInstagram } from "react-icons/ai";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Gerrit VanderStoel's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className="bg-indigo-400 h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl">Gerrit's Portfolio</h1>
            <ul className="flex items-center">
              <li>
                <a
                  href="#About"
                  className="bg-slate-600 text-white px-2 py-1 ml-8 scroll-behavior: smooth;"
                >
                  {" "}
                  About
                </a>
              </li>
              <li>
                <a
                  href="#Projects"
                  className="bg-slate-600 text-white px-2 py-1 ml-8"
                >
                  {" "}
                  Projects
                </a>
              </li>
              <li>
                <a
                  href="#Experience"
                  className="bg-slate-600 text-white px-2 py-1 ml-8"
                >
                  {" "}
                  Experience
                </a>
              </li>
              <li>
                <a
                  href="#Contact"
                  className="bg-slate-600 text-white px-2 py-1 ml-8"
                >
                  {" "}
                  Contact
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-slate-100 font-medium">
              Gerrit VanderStoel{" "}
            </h2>
            <h3 className="text-2xl py-2 mb-8 text-slate-100 font-medium">
              Full Stack Developer
            </h3>
            <p>
              Hi! My name is Gerrit VanderStoel and I’m currently a computer
              science student who enjoys using technology as a way to problem
              solve and create innovative solutions. I have elevated my ability
              to work collaboratively with various teams through my past
              experiences both in my professional and educational careers.
            </p>
            <Image
              src="/portrait.jpg"
              width={200}
              height={200}
              className="rounded-full mx-auto image-margin"
            ></Image>
          </div>
          <div className="flex justify-center text-6xl gap-24 ">
            <a
              href="https://github.com/ca5eman"
              target="_blank"
              rel="noopener noreferrer"
            >
              <AiFillGithub />
            </a>
            <a
              href="https://instagram.com/gerritv_29"
              target="_blank"
              rel="noopener noreferrer"
            >
              <AiFillInstagram />
            </a>
            <a
              href="https://www.linkedin.com/in/gerrit-vanderstoel-3851371a7/"
              target="_blank"
              rel="noopener noreferrer"
            >
              <AiFillLinkedin />
            </a>
          </div>
        </section>
        <section id="Projects" className="bg-indigo-400 h-screen">
          <div className="text-left text-white">
            <h3 className="text-5xl py-2"> Projects </h3>
          </div>
          <ul className="flex text-2xl justify-between py-4 gap-20 font-medium">
            <li>
              <h4>SuppCompare</h4>
              <p className="snap-center mt-28">
                SuppCompare is a mobile app developed for IOS in which users can
                take control of their fitness journey. Namely, users can compare
                a range of supplements to see what fits best for their needs
              </p>
            </li>
            <li>
              <h4>Star Wars Minigame</h4>
              <p className="snap-center mt-28">
                {" "}
                A project from a simpler time in C++. This project was made in
                collaboration with a group during freshman year of college. The
                goal of this game is to destroy incoming tie fighters as an
                X-WING, in the same vein as space invaders.
              </p>
            </li>
            <li>
              <h4>Personal Portfolio V1/V2</h4>
              <p className="snap-center mt-28">
                This encompasses both the current portfolio website you are
                viewing, which is always being worked on, and the first
                iteration created last year. Version 2 is created with tailwind
                and react while the old website is just simple html and css.
              </p>
            </li>
          </ul>
        </section>
        <section id="Experience" className="bg-indigo-400 h-screen">
          <div className="text-right text-white">
            <h3 className="text-4xl py-2">Experience</h3>
          </div>
          <ul className="flex text-2xl justify-between py-4 gap-20 font-medium">
            <li>
              <h4>In-N-Out Associate</h4>
              <p className="snap-center mt-28">
                June 2020 to October 2023 Prepared produce for the restaurant,
                such as slicing tomatoes and skinning potatoes. Maintained
                cleanliness in the kitchen, back of the store and the dining
                area for our guests. Communicated with a team in a high pressure
                environment to problem solve and stay efficient.
              </p>
            </li>
            <li>
              <h4>Apple Specialist</h4>
              <p className="snap-center mt-28">
                {" "}
                August 2022 - Present Presented solutions for customers based on
                personal needs and constraints. Gave support to customers
                unfamiliar with the Apple Ecosystem. Collaborated with
                technicians, experts, pros and other sects of the store to bring
                our customers the best experience possible in store.
              </p>
            </li>
            <li>
              <h4> LEGOLAND Lifeguard</h4>
              <p className="snap-center mt-28">
                April 2019 to October 2019 Insured safety of guests at the
                waterpark at all times. Assisted those in need of help (lost
                children, injured guests, guests in distress). Problem solved
                via audits with coworkers in and out of the water. Interacted
                with guests to help improve their visit to the park.{" "}
              </p>
            </li>
          </ul>
        </section>
        <section id="Contact" className="bg-indigo-400 h-screen">
          <div className="text-center text-white">
            <h3 className="text-4xl py-2"></h3>
            <Page></Page>
          </div>
        </section>
      </main>
    </div>
  );
}
